### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by ans82** [MGersting111/cafe-app#47]
We want to let our app run!

Heroku is the classic. However the pure free developer / hobby dyno tier is gone as far as i see. Still heroku might be the way to go, albeit small cost will arise. But i guess we can take the cheapest tariff and experiment a bit with it.

Otherwise: I checked current providers and i think fly.io could also be a suitable simple hoster.
They have a command line tool for the actual deployment: `brew install flyctl` and from what i see also great docs! This should help: https://fly.io/docs/rails/getting-started/existing/
There are still some issues to be solved though: We need to checkout whether / how we can provision a postgres database. I think it will work... but one has to read the docs :D

**Comment by MGersting111** [comment]
All done!
